### ISSUE TITLE
Path difference

### ISSUE THREAD

**Issue by spea1** [Alignak-monitoring-contrib/alignak-checks-nrpe#1]
Path difference in Alignak checks package for NRPE installation from source files.

Alignak default: "etc/alignak/arbiter_cfg/resource.d/paths.cfg"
...
;-- Location of the plugins for Alignak
$PLUGINSDIR$=**/var/lib/alignak/libexec**
..."

Install the package from the source files:*

...
;# Copy plugin files
cp -R alignak_checks_nrpe/plugins/\* **/usr/local/libexec/alignak**"

;# Test remote access with the plugins files:
**/usr/local/var/lib/alignak/libexec/check_nrpe** -H 127.0.0.1 -t 9 -u -c check_load

;# Alignak nrpe commands example
...
command_line **ALIGNAKLIB**/check_nrpe -H $HOSTADDRESS$ -t 10 -u
...

**Comment by mohierf** [comment]
Fixed
